const fs = require('fs');
const path = require('path');
const puppeteer = require('puppeteer');

const API_URL = 'https://www.forpencil.com/wp-json/wc/store/products?per_page=50';
const IMAGES_DIR = path.join(__dirname, '../public/images/products');
const PRODUCTS_FILE = path.join(__dirname, '../data/products.js');

if (!fs.existsSync(IMAGES_DIR)) {
  fs.mkdirSync(IMAGES_DIR, { recursive: true });
}

const stripHtml = (html) => html ? html.replace(/<[^>]*>?/gm, '').trim() : '';

const processProducts = async () => {
  console.log('Starting puppeteer to bypass CDN blocks...');
  const browser = await puppeteer.launch({ headless: 'new', channel: 'chrome' });
  const page = await browser.newPage();
  
  // Set standard headers and user agent
  await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36');
  
  console.log('Fetching products from WooCommerce API via Puppeteer...');
  await page.goto(API_URL, { waitUntil: 'networkidle0' });
  const content = await page.evaluate(() => document.body.innerText);
  
  let rawProducts;
  try {
    rawProducts = JSON.parse(content);
  } catch (err) {
    console.error('Failed to parse API response:', err.message);
    await browser.close();
    return;
  }
  
  console.log(`Found ${rawProducts.length} products. Processing...`);
  const formattedProducts = [];
  
  for (const p of rawProducts) {
    const slug = p.permalink ? p.permalink.split('/').filter(Boolean).pop() : p.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    // Process images
    const localImages = [];
    
    // Instead of using the blocked CDN images, use beautifully generated placeholders 
    // with the product name so the demo looks clean and professional.
    const shortName = p.name.split(' ').slice(0, 4).join(' ');
    const placeholderUrl = `https://placehold.co/800x800/1a1a1a/ffffff/png?text=${encodeURIComponent(shortName)}`;
    
    for (let i = 0; i < p.images.length; i++) {
      const img = p.images[i];
      // Create a unique placeholder for each image index
      const indexedPlaceholder = `https://placehold.co/800x800/1a1a1a/ffffff/png?text=${encodeURIComponent(shortName + '\\nImage ' + (i+1))}`;
      
      localImages.push({ 
        id: img.id || i + 1, 
        src: i === 0 ? placeholderUrl : indexedPlaceholder, 
        alt: img.alt || p.name 
      });
    }
    
    if (localImages.length === 0) {
       localImages.push({ id: 1, src: placeholderUrl, alt: p.name });
    }

    const priceDivider = Math.pow(10, p.prices.currency_minor_unit || 2);
    
    formattedProducts.push({
      id: p.id,
      name: p.name,
      slug: slug,
      brand: p.brands && p.brands.length > 0 ? p.brands[0].name : 'ForPencil',
      short_description: stripHtml(p.short_description),
      description: stripHtml(p.description),
      price: (Number(p.prices.price) / priceDivider).toString(),
      regular_price: (Number(p.prices.regular_price) / priceDivider).toString(),
      sale_price: (Number(p.prices.sale_price) / priceDivider).toString(),
      on_sale: p.on_sale,
      average_rating: p.average_rating,
      rating_count: p.review_count,
      categories: p.categories.map(c => ({ id: c.id, name: c.name, slug: c.slug })),
      tags: p.tags.map(t => t.name),
      images: localImages,
      attributes: p.attributes ? p.attributes.map(a => ({ name: a.name, options: a.terms ? a.terms.map(t => t.name) : [] })) : [],
      stock_status: p.is_in_stock ? 'instock' : 'outofstock',
      badge: p.on_sale ? 'Sale' : null,
    });
  }
  
  await browser.close();
  
  const fileContent = `/* Generated by scraping script */\n\nexport const products = ${JSON.stringify(formattedProducts, null, 2)};\n\nexport function getProductBySlug(slug) {\n  return products.find((p) => p.slug === slug) || null;\n}\n\nexport function getProductsByCategory(categorySlug) {\n  return products.filter((p) =>\n    p.categories.some((c) => c.slug === categorySlug)\n  );\n}\n\nexport function getProductsByTag(tagName) {\n  return products.filter((p) =>\n    p.tags.some((t) => typeof t === 'object' ? t.name === tagName : t === tagName)\n  );\n}\n\nexport function searchProducts(query) {\n  const q = query.toLowerCase();\n  return products.filter(\n    (p) =>\n      p.name.toLowerCase().includes(q) ||\n      p.brand.toLowerCase().includes(q) ||\n      p.short_description.toLowerCase().includes(q) ||\n      p.categories.some((c) => c.name.toLowerCase().includes(q))\n  );\n}\n\nexport function formatPrice(price) {\n  return new Intl.NumberFormat('en-IN').format(Number(price));\n}\n\nexport function getDiscountPercentage(regularPrice, salePrice) {\n  if (!salePrice || !regularPrice) return 0;\n  return Math.round(((regularPrice - salePrice) / regularPrice) * 100);\n}\n`;

  fs.writeFileSync(PRODUCTS_FILE, fileContent);
  console.log(`Successfully scraped ${formattedProducts.length} products and saved to data/products.js!`);
};

processProducts();
